project:
  type: website
  output-dir: docs

website:
  title: "Edoardo A. Viganò"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: personal.qmd
        text: Personal
    website:
  google-analytics: "G-V76XCX9MG0"
  favicon: icon.png

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

